---
- name: Create file
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: create a file that is larger than 2GB
      shell: dd if=/dev/urandom of=/tmp/file.txt bs=2200000 count=1000
    - name: create 3 files with a custom date
      shell: touch -d 20180501  /tmp/file{1..3}